#!/usr/bin/env bash

# Todo
# :sed -e 's/^#!\/bin\/cat//' {{STDIN}}
# My bash skillz must be exercised later on. Sometimes i HATE sed.. And bash...
##:Self::3 But I Love the idea of STRINGS in bash... gotta be reversed that lan)guage for a better cause

